---
title: "Weight Boxplots"
author: "Elizabeth"
date: "19 October 2018"
output: html_document
---
title: "Prelim Boxplots"
author: "Elizabeth"
date: "19 October 2018"
output: html_document
---

```{r}
#importing data
library(dplyr)
library(readr)
library(readr)
LabHarvestR <- read_csv("LabHarvestR.csv")
```

```{r}
#making things factors
LabHarvestR$Treatment <- as.factor(LabHarvestR$Treatment)
LabHarvestR$Harvest<-as.factor(LabHarvestR$Harvest)
LabHarvestR$Tag<-as.factor(LabHarvestR$Tag)
```

```{r}
#Subsetting for Boxplots
LabHarvest_H1 <- subset(LabHarvestR,Harvest=="1")
LabHarvest_H1_VS <- subset(LabHarvest_H1,Species=="VS")
LabHarvest_H1 <- subset(LabHarvestR,Harvest=="1")
LabHarvest_H1_VE <- subset(LabHarvest_H1,Species=="VE")
LabHarvest_H2 <- subset(LabHarvestR,Harvest=="2")
LabHarvest_H2_VS <- subset(LabHarvest_H1,Species=="VS")
LabHarvest_H2 <- subset(LabHarvestR,Harvest=="2")
LabHarvest_H2_VE <- subset(LabHarvest_H1,Species=="VE")
LabHarvest_H3 <- subset(LabHarvestR,Harvest=="3")
LabHarvest_H3_VS <- subset(LabHarvest_H1,Species=="VS")
LabHarvest_H3 <- subset(LabHarvestR,Harvest=="3")
LabHarvest_H3_VE <- subset(LabHarvest_H1,Species=="VE")
```

```{r}
#Boxplots for Total Dry Biomass
plot(Total_DW~Treatment,data=LabHarvest_H1_VS, main= "Total DW H1 VS")
plot(Total_DW~Treatment,data=LabHarvest_H1_VE, main= "Total DW H1 VE")
plot(Total_DW~Treatment,data=LabHarvest_H2_VS, main= "Total DW H2 VS")
plot(Total_DW~Treatment,data=LabHarvest_H2_VE, main= "Total DW H2 VE")
plot(Total_DW~Treatment,data=LabHarvest_H3_VS, main= "Total DW H3 VS")
plot(Total_DW~Treatment,data=LabHarvest_H3_VE, main= "Total DW H3 VE")
```

```{r}
#Boxplots for Height
plot(Height~Treatment,data=LabHarvest_H1_VS, main= "Height H1 VS")
plot(Height~Treatment,data=LabHarvest_H1_VE, main= "Height H1 VE")
plot(Height~Treatment,data=LabHarvest_H2_VS, main= "Height H2 VS")
plot(Height~Treatment,data=LabHarvest_H2_VE, main= "Height H2 VE")
plot(Height~Treatment,data=LabHarvest_H3_VS, main= "Height H3 VS")
plot(Height~Treatment,data=LabHarvest_H3_VE, main= "Height H3 VE")
```

```{r}
#Boxplots for Below ground biomass
plot(BG_DW~Treatment,data=LabHarvest_H1_VS, main= "Below DW H1 VS")
plot(BG_DW~Treatment,data=LabHarvest_H1_VE, main= "Below DW H1 VE")
plot(BG_DW~Treatment,data=LabHarvest_H2_VS,main= "Below DW H2 VS")
plot(BG_DW~Treatment,data=LabHarvest_H2_VE,main= "Below DW H2 VE")
plot(BG_DW~Treatment,data=LabHarvest_H3_VS,main= "Below DW H3 VS")
plot(BG_DW~Treatment,data=LabHarvest_H3_VE, main= "Below DW H3 VE")
```

```{r}
#Boxplots for Leaf dry weight 
plot(Leaves_DW~Treatment,data=LabHarvest_H1_VS, main= "Leaf DW H1 VS")
plot(Leaves_DW~Treatment,data=LabHarvest_H1_VE, main= "Leaf DW H1 VE")
plot(Leaves_DW~Treatment,data=LabHarvest_H2_VS,main= "Leaf DW H2 VS")
plot(Leaves_DW~Treatment,data=LabHarvest_H2_VE,main= "Leaf DW H2 VE")
plot(Leaves_DW~Treatment,data=LabHarvest_H3_VS,main= "Leaf DW H3 VS")
plot(Leaves_DW~Treatment,data=LabHarvest_H3_VE, main= "Leaf DW H3 VE")
```

```{r}
#Boxplots for Leaf dry weight
plot(Stem_DW~Treatment,data=LabHarvest_H1_VS, main= "Stem DW H1 VS")
plot(Stem_DW~Treatment,data=LabHarvest_H1_VE, main= "Stem DW H1 VE")
plot(Stem_DW~Treatment,data=LabHarvest_H2_VS,main= "Stem DW H2 VS")
plot(Stem_DW~Treatment,data=LabHarvest_H2_VE,main= "Stem DW H2 VE")
plot(Stem_DW~Treatment,data=LabHarvest_H3_VS,main= "Stem DW H3 VS")
plot(Stem_DW~Treatment,data=LabHarvest_H3_VE, main= "Stem DW H3 VE")
```

