---
title: "LabExp_Oct"
author: "Elizabeth"
date: "19 October 2018"
output: html_document
---

#importing data
```{r}
library(dplyr)
library(readr)
LabHarvest<-read_csv("LabHarvestR.csv")
```

#making things factors
```{r}
LabHarvest$Treatment <- as.factor(LabHarvest$Treatment)
LabHarvest$Harvest<-as.factor(LabHarvest$Harvest)
LabHarvest$Tag<-as.factor(LabHarvest$Tag)
```

#subseting 
```{r}
LabHarvest_H2 <- subset(LabHarvest,Harvest=="2")
```

#linear model 
```{r}
LabHarvest_H2_N.m<-lm(AG_DW~Treatment+Nodules_W+Species, data= LabHarvest_H2)
summary(LabHarvest_H2_N.m)
```

#checking residuals 
```{r}
LabHarvest_H2.resid<-resid(LabHarvest_H2_N.m)
shapiro.test(LabHarvest_H2.resid)
bartlett.test(Height~Species, data= LabHarvest_H2)
```

#general linear model 
```{r}
LabHarvest_H2 <- subset(LabHarvest,Harvest=="2")
LabHarvest_H2_VS<-subset(LabHarvest_H2,Species=="VS")
LabHarvest_H2_VS.m<-glm(Nodules_Present~Treatment, family=binomial, data=LabHarvest_H2_VS)
summary(LabHarvest_H2_VS.m)
``` 

#linear assumption graphs 
```{r}
plot(LabHarvest_H2_N.m)
```



