---
title: "H1 Basic Models"
author: "Elizabeth"
date: "7 November 2018"
output: html_document
---
```{r}
library(readxl)
LabHarveste <- read_excel("C:/Users/telfo/Desktop/LabHarveste.xlsx")
View(LabHarveste)
LabHarvest<-LabHarveste
library(ggplot2)
library(agridat)
```

```{r}
#setting factors
LabHarvest$Treatment <- as.factor(LabHarvest$Treatment)
LabHarvest$Harvest<-as.factor(LabHarvest$Harvest)
LabHarvest$Tag<-as.factor(LabHarvest$Tag)
```

```{r}
#subsetting
LabHarvest_H1 <- subset(LabHarvest,Harvest=="1")
LabHarvest_H1_VS <- subset(LabHarvest_H1,Species=="VS")
LabHarvest_H1 <- subset(LabHarvest,Harvest=="1")
LabHarvest_H1_VE <- subset(LabHarvest_H1,Species=="VE")
LabHarvest_H2 <- subset(LabHarvest,Harvest=="2")
LabHarvest_H2_VS <- subset(LabHarvest_H2,Species=="VS")
LabHarvest_H2 <- subset(LabHarvest,Harvest=="2")
LabHarvest_H2_VE <- subset(LabHarvest_H2,Species=="VE")
LabHarvest_H3 <- subset(LabHarvest,Harvest=="3")
LabHarvest_H3_VS <- subset(LabHarvest_H3,Species=="VS")
LabHarvest_H3 <- subset(LabHarvest,Harvest=="3")
LabHarvest_H3_VE <- subset(LabHarvest_H3,Species=="VE")

LabHarvest_VS<-subset(LabHarvest, Species=="VS")
LabHarvest_VE<-subset(LabHarvest, Species=="VE")
```

```{r}
theme.clean <- function(){
  theme_bw()+
    theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 1, hjust = 1),
          axis.text.y = element_text(size = 12),
          axis.title.x = element_text(size = 14, face = "plain"),             
          axis.title.y = element_text(size = 14, face = "plain"),             
          panel.grid.major.x = element_blank(),                                          
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_blank(),  
          plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
          plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
          legend.text = element_text(size = 12, face = "italic"),          
          legend.title = element_blank(),                              
          legend.position = c(0.9, 0.9))
}
```

#Total weight vs Species + Treatment 
```{r}
(LabHarvest_H1_TDW.p <- ggplot(LabHarvest_H1, aes(Tag, Total_DW)) + geom_boxplot(fill = "#CD3333", alpha = 0.8, colour = "#8B2323") + theme.clean() +  theme(axis.text.x = element_text(size = 12, angle = 0)) + labs(x = "Species & Treatment (%)", y = "Total Dry weight (grams)"))

LabHarvest_H1_TDW.m<-lm(Total_DW~Treatment + Species, data= LabHarvest_H1)
summary(LabHarvest_H1_TDW.m)

LabHarvest_H1_VS_TDW.m<-lm(Total_DW~Treatment, data= LabHarvest_H1_VS)
summary(LabHarvest_H1_VS_TDW.m)

LabHarvest_H1_VE_TDW.m<-lm(Total_DW~Treatment, data= LabHarvest_H1_VE)
summary(LabHarvest_H1_VE_TDW.m)

#not significant at all 

```

#Belowground weight vs Treatment + Species
```{r}
(LabHarvest_H1_BGDW.p <- ggplot(LabHarvest_H1, aes(Tag, BG_DW)) + geom_boxplot(fill = "#CD3333", alpha = 0.8, colour = "#8B2323") + theme.clean() +  theme(axis.text.x = element_text(size = 12, angle = 0)) + labs(x = "Species & Treatment (%)", y = " Below Ground Dry Weight (grams)"))

LabHarvest_H1_BGDW.m<-lm(BG_DW~Treatment + Species, data= LabHarvest_H1)
summary(LabHarvest_H1_BGDW.m)

H1_BGDW.resid<-resid(LabHarvest_H1_BGDW.m)
shapiro.test(H1_BGDW.resid)

bartlett.test(LabHarvest_H1$BG_DW,LabHarvest_H1$Treatment)
```

#Aboveground weight vs Treatment + Species
```{r}
(H1_AGDW.p <- ggplot(LabHarvest_H3, aes(Tag, AG_DW)) 
    +  geom_boxplot(fill = "#CD3333", alpha = 0.8, colour = "#8B2323") 
    +  theme.clean()   
    + theme(axis.text.x = element_text(size = 12, angle = 0)) + labs(x = "Species & Treatment (%)", y = "Aboveground Dry Weight (grams)"))
    
LabHarvest_H1_AGDW.m<-lm(AG_DW~Treatment + Species, data= LabHarvest_H1)
summary(LabHarvest_H1_AGDW.m)

H1_AGDW.resid<-resid(LabHarvest_H1_AGDW.m)
shapiro.test(H1_AGDW.resid)

bartlett.test(LabHarvest_H1$AG_DW,LabHarvest_H1$Treatment)

```

#Leaf biomass Vs Treatment + Species
```{r}
(LabHarvest_H1_leaf.p <- ggplot(LabHarvest_H1, aes(Tag, Leaves_DW)) + geom_boxplot(fill = "#CD3333", alpha = 0.8, colour = "#8B2323") + theme.clean() +  theme(axis.text.x = element_text(size = 12, angle = 0)) + labs(x = "Species & Treatment (%)", y = "Leaf Dry weight (grams)"))

LabHarvest_H1_leafDW.m<-lm(Leaves_DW~Treatment + Species , data= LabHarvest_H1)
summary(LabHarvest_H1_leafDW.m)

H1_leafDW.resid<-resid(LabHarvest_H1_leafDW.m)
shapiro.test(H1_leafDW.resid)

bartlett.test(LabHarvest_H1$Leaves_DW,LabHarvest_H1$Treatment)

```


#Height vs Treatment + Species
```{r}
(LabHarvest_H1_Height.p <- ggplot(LabHarvest_H1, aes(Tag, Height)) + geom_boxplot(fill = "#CD3333", alpha = 0.8, colour = "#8B2323") + theme.clean() +  theme(axis.text.x = element_text(size = 12, angle = 0)) + labs(x = "Species & Treatment (%)", y = "Height (mm)"))

LabHarvest_H1_Height.m<-lm(Height~Treatment + Species , data= LabHarvest_H1)
summary(LabHarvest_H1_Height.m)

#treatment + species is not significant

LabHarvest_H1_VS_Height.m<-lm(Height~Treatment , data= LabHarvest_H1_VS)
summary(LabHarvest_H1_VS_Height.m)

H1_VS_Height.resid<-resid(LabHarvest_H1_VS_Height.m)
shapiro.test(H1_VS_Height.resid)

bartlett.test(LabHarvest_H1_VS$Height,LabHarvest_H1_VS$Treatment)

LabHarvest_H1_VE_Height.m<-lm(Height~Treatment  , data= LabHarvest_H1_VE)
summary(LabHarvest_H1_VE_Height.m)

H1_VE_Height.resid<-resid(LabHarvest_H1_VE_Height.m)

shapiro.test(H1_VE_Height.resid)

bartlett.test(LabHarvest_H1_VE$Height,LabHarvest_H1_VE$Treatment)
```

#Stem vs Treatment + Species
```{r}
(LabHarvest_H1_stalk.p <- ggplot(LabHarvest_H1, aes(Tag, Stem_DW)) + geom_boxplot(fill = "#CD3333", alpha = 0.8, colour = "#8B2323") + theme.clean() +  theme(axis.text.x = element_text(size = 12, angle = 0)) + labs(x = "Species & Treatment (%)", y = "Stem Dry Weight (grams)"))

LabHarvest_H3_stalk.m<-lm(Stem_DW~Treatment, data= LabHarvest_H3)
summary(LabHarvest_H3_stalk.m)

LabHarvest_H3_VS_stalk.m<-lm(Stem_DW~Treatment, data= LabHarvest_H3_VS)
summary(LabHarvest_H3_VS_stalk.m)

LabHarvest_H3_VE_stalk.m<-lm(Stem_DW~Treatment, data= LabHarvest_H3_VE)
summary(LabHarvest_H3_VE_stalk.m)
```

#Examing the effects of Nodules on V.Sieb

#Nodule Boxplots 
```{r}
(LabHarvest_H1_Nodules.p <- ggplot(LabHarvest_H1_VS, aes(Tag, Nodule)) + geom_boxplot(fill = "#CD3333", alpha = 0.8, colour = "#8B2323") + theme.clean() +  theme(axis.text.x = element_text(size = 12, angle = 0)) + labs(x = "Species & Treatment (%)", y = "Nodule Count"))

(LabHarvest_H1_NodulesW.p <- ggplot(LabHarvest_H1_VS, aes(Tag, Nodules_W)) + geom_boxplot(fill = "#CD3333", alpha = 0.8, colour = "#8B2323") + theme.clean() +  theme(axis.text.x = element_text(size = 12, angle = 0)) + labs(x = "Species & Treatment (%)", y = "Nodule Weight (grams)"))
```

#GLM for Nodule Presence 
```{r}
LabHarvest_H1_Nodule.m <-glm(Nodules_Present~Treatment, family= binomial, data=LabHarvest_H1)
summary(LabHarvest_H1_Nodule.m)
```

#Nodule count as a factor

#Nodule count vs Height 
```{r}
LabHarvest_H1_VS_HNOD.m<-lm(Height~Treatment + Nodule, data= LabHarvest_H1_VS)
summary(LabHarvest_H1_VS_HNOD.m)
```